spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newuser?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 971283389730-2hucolqgub3klndoiqvk4cdk0lphams2.apps.googleusercontent.com
            clientSecret: DyYo3Qqav-35bQFTsnWUg2js
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          naver:
            clientId: 9l9Geet5gFFXQL8PupSW
            clientSecret: 7qRAQf9wpV
            redirectUri: "{baseUrl}/oauth2/callback/naver"
            authorization_grant_type: authorization_code
            scope: name,profile
            client-name : Naver
        #          kakao:
        #            clientID: 1b9c543308b4d8ddd5f93c15b9b039b8
        #            clientSecret: Kyqqro8rOWriFunFZGv0T5Abb3SmXIIP
        #            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        #            authorization_grant_type: authorization_code
        #            scope: profile

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: response
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
